<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Save as private' => '保存为私密',
    'Save as public' => '保存为公开',
    'key' => '',
    'Are you sure you want to private this note?' => '你确实要讲该笔记设置为私密么？',
    'Are you sure you want to public this note?' => '你确实要公开该笔记么？',
    'Content' => '内容',
    'Create Note' => '创建笔记',
    'Created At' => '创建时间',
    'Expired At' => '过期时间',
    'Format' => '语法格式',
    'Note created.' => '笔记已经创建',
    'Note does not exist.' => '笔记不存在',
    'Note has been deleted' => '笔记已经删除',
    'Note updated.' => '笔记更新成功',
    'Notes' => '笔记',
    'Notes have been made private.' => '笔记已经私密。',
    'Notes have been made public.' => '笔记已经公开。',
    'Operation' => '操作',
    'Private' => '私密',
    'Public' => '公开',
    'Title' => '标题',
    'Type' => '类型',
    'Update' => '更新',
    'Update Note: ' => '更新笔记：',
    'Updated At' => '更新时间',
    'Views' => '查看数',
];
