<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '你确定要删除该项目？',
    'Collect' => '',
    'Collected' => '',
    'ID' => '',
    'UUID' => '',
    'User ID' => '',
    'Are you sure you want to private this note?' => '你确实要将该笔记设置为私密么？',
    'Are you sure you want to public this note?' => '你确实要公开该笔记么？',
    'Batch Deletion' => '批量删除',
    'Collection of notes' => '收藏的笔记',
    'Content' => '内容',
    'Create' => '创建',
    'Create Note' => '创建笔记',
    'Created At' => '创建时间',
    'Delete Note' => '删除笔记',
    'Edit' => '修改',
    'Expired At' => '过期时间',
    'Format' => '语法格式',
    'His Collection of notes' => '他收藏的笔记',
    'His Notes' => '他的笔记',
    'Learned something new？ Write it down' => '今天学到了什么呢？ 快用笔记记录一下吧',
    'Loading...' => '加载中...',
    'Manage Note' => '笔记管理',
    'My Collection of notes' => '我收藏的笔记',
    'My Notes' => '我的笔记',
    'Next page' => '下一页',
    'No popular notes' => '暂无热门笔记',
    'Note created.' => '笔记已经创建',
    'Note does not exist.' => '笔记不存在',
    'Note has been deleted' => '笔记已经删除',
    'Note updated.' => '笔记更新成功',
    'Notes' => '笔记',
    'Notes have been made private.' => '笔记已经私密。',
    'Notes have been made public.' => '笔记已经公开。',
    'Operation' => '操作',
    'Please choose' => '请选择',
    'Popular Notes' => '热门笔记',
    'Previous page' => '上一页',
    'Private' => '私密',
    'Public' => '公开',
    'Published in' => '发布于',
    'Remove' => '删除',
    'Reset' => '重置',
    'Save as private' => '保存为私密',
    'Save as public' => '保存为公开',
    'Search' => '搜索',
    'Sure?' => '你确定？',
    'Title' => '标题',
    'Type' => '类型',
    'Update' => '更新',
    'Update Note' => '更新笔记',
    'Update Note: ' => '更新笔记：',
    'Updated At' => '更新时间',
    'Views' => '查看数',
    'Write a note' => '记笔记',
    'views' => '查看',
];
