<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use xutl\select2\Select2;
use yuncms\note\models\Note;

/* @var $this yii\web\View */
/* @var $model yuncms\note\models\Note */
/* @var $form yii\widgets\ActiveForm */
?>
<?php $form = ActiveForm::begin(['layout' => 'horizontal']); ?>

<?= $form->field($model, 'title') ?>
<?= $form->field($model, 'format')->widget(Select2::className(), [
    'items' => [
        '' => Yii::t('note', 'Please choose'),
        'bash' => 'Bash',
        'xml' => 'XML',
        'cpp' => 'C++',
        'cs' => 'C#',
        'css' => 'CSS',
        'delphi' => 'Delphi',
        'php' => 'PHP',
        'python' => 'Python',
        'django' => 'Django',
        'apache' => 'Apache',
        'applescript' => 'Apple Script',
        'cmake' => 'CMake',
        'dockerfile' => 'Dockerfile',
        'erlang' => 'Erlang',
        'go' => 'Go',
        'ini' => 'Ini',
        'java' => 'Java',
        'javascript' => 'JavaScript',
        'json' => 'JSON',
        'ruby' => 'Ruby',
        'sql' => 'SQL',
        'yaml' => 'YAML',
        'zephir' => 'Zephir',

        '1c' => '1C',
        'abnf' => 'Augmented Backus-Naur Form',
        'accesslog' => 'Access log',
        'actionscript' => 'Action Script',
        'ada' => 'Ada',
        'arduino' => 'Arduino',
        'armasm' => 'ARM Assembly',
        'asciidoc' => 'Ascii Doc',
        'aspectj' => 'AspectJ',
        'autohotkey' => 'AutoHotkey',
        'autoit' => 'AutoIt',
        'avrasm' => 'AVR Assembler',
        'awk' => 'Awk',
        'axapta' => 'Axapta',
        'basic' => 'Basic',
        'bnf' => 'Backus–Naur Form',
        'brainfuck' => 'Brainfuck',
        'cal' => 'C/AL',
        'capnproto' => 'Cap’n Proto',
        'ceylon' => 'Ceylon',
        'clean' => 'Clean',
        'clojure' => 'Clojure',
        'clojure-repl' => 'Clojure REPL',
        'coffeescript' => 'Coffee Script',
        'coq' => 'Coq',
        'cos' => 'Caché Object Script',
        'crmsh' => 'crmsh',
        'crystal' => 'Crystal',
        'csp' => 'CSP',
        'd' => 'D',
        'dart' => 'Dart',
        'diff' => 'Diff',
        'dns' => 'DNS Zone file',
        'dos' => 'DOS .bat',
        'dsconfig' => 'dsconfig',
        'dts' => 'Device Tree',
        'dust' => 'Dust',
        'ebnf' => 'Extended Backus-Naur Form',
        'elixir' => 'Elixir',
        'elm' => 'Elm',
        'erb' => 'ERB (Embedded Ruby)',
        'erlang-repl' => 'Erlang REPL',
        'excel' => 'Excel',
        'fix' => 'FIX',
        'flix' => 'Flix',
        'fortran' => 'Fortran',
        'fsharp' => 'F#',
        'gams' => 'GAMS',
        'gauss' => 'GAUSS',
        'gcode' => 'G-code (ISO 6983)',
        'gherkin' => 'Gherkin',
        'glsl' => 'GLSL',
        'golo' => 'Golo',
        'gradle' => 'Gradle',
        'groovy' => 'Groovy',
        'haml' => 'Haml',
        'handlebars' => 'Handlebars',
        'haskell' => 'Haskell',
        'haxe' => 'Haxe',
        'hsp' => 'HSP',
        'htmlbars' => 'HTMLBars',
        'http' => 'HTTP',
        'inform7' => 'Inform 7',
        'irpf90' => 'IRPF90',
        'julia' => 'Julia',
        'kotlin' => 'Kotlin',
        'lasso' => 'Lasso',
        'ldif' => 'LDIF',
        'less' => 'Less',
        'lisp' => 'Lisp',
        'livecodeserver' => 'LiveCode',
        'livescript' => 'LiveScript',
        'llvm' => 'LLVM IR',
        'lsl' => 'Linden Scripting Language',
        'lua' => 'Lua',
        'makefile' => 'Makefile',
        'markdown' => 'Markdown',
        'mathematica' => 'Mathematica',
        'matlab' => 'Matlab',
        'maxima' => 'Maxima',
        'mel' => 'MEL',
        'mercury' => 'Mercury',
        'mipsasm' => 'MIPS Assembly',
        'mizar' => 'Mizar',
        'mojolicious' => 'Mojolicious',
        'monkey' => 'Monkey',
        'moonscript' => 'MoonScript',
        'nginx' => 'Nginx',
        'nimrod' => 'Nimrod',
        'nix' => 'Nix',
        'nsis' => 'NSIS',
        'objectivec' => 'Objective-C',
        'ocaml' => 'OCaml',
        'openscad' => 'OpenSCAD',
        'oxygene' => 'Oxygene',
        'parser3' => 'Parser3',
        'perl' => 'Perl',
        'pf' => 'pf',
        'pony' => 'Pony',
        'powershell' => 'PowerShell',
        'processing' => 'Processing',
        'profile' => 'Python profile',
        'prolog' => 'Prolog',
        'protobuf' => 'Protocol Buffers',
        'puppet' => 'Puppet',
        'purebasic' => 'Pure BASIC',
        'q' => 'Q',
        'qml' => 'QML',
        'r' => 'R',
        'rib' => 'RenderMan RIB',
        'roboconf' => 'Roboconf',
        'rsl' => 'RenderMan RSL',
        'ruleslanguage' => 'Oracle Rules Language',
        'rust' => 'Rust',
        'scala' => 'Scala',
        'scheme' => 'Scheme',
        'scilab' => 'scilab',
        'scss' => 'SCSS',
        'smali' => 'Smali',
        'smalltalk' => 'Smalltalk',
        'sml' => 'SML',
        'sqf' => 'SQF',
        'stan' => 'Stan',
        'stata' => 'Stata',
        'step21' => 'STEP Part 21',
        'stylus' => 'Stylus',
        'subunit' => 'SubUnit',
        'swift' => 'Swift',
        'taggerscript' => 'Tagger Script',
        'tap' => 'Test Anything Protocol',
        'tcl' => 'Tcl',
        'tex' => 'TeX',
        'thrift' => 'Thrift',
        'tp' => 'TP',
        'twig' => 'Twig',
        'typescript' => 'TypeScript',
        'vala' => 'Vala',
        'vbnet' => 'VB.NET',
        'vbscript' => 'VBScript',
        'vbscript-html' => 'VBScript in HTML',
        'verilog' => 'Verilog',
        'vhdl' => 'VHDL',
        'vim' => 'Vim Script',
        'x86asm' => 'Intel x86 Assembly',
        'xl' => 'XL',
        'xquery' => 'XQuery',
    ]
]) ?>
<?= $form->field($model, 'content')->textarea() ?>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <?php if ($model->isNewRecord): ?>
                <?= Html::submitButton(Yii::t('note', 'Save as public'), [
                    'class' => 'btn btn-success',
                    'name' => 'Note[type]',
                    'value' => Note::TYPE_PUBLIC
                ]) ?>

                <?= Html::submitButton(Yii::t('note', 'Save as private'), [
                    'class' => 'btn pub-btn',
                    'name' => 'Note[type]',
                    'value' => Note::TYPE_PRIVATE
                ]) ?>
            <?php else: ?>
                <?=
                Html::submitButton(Yii::t('note', 'Update'), ['class' => 'btn btn-primary'])
                ?>
            <?php endif; ?>
        </div>
    </div>
<?php ActiveForm::end(); ?>